### ISSUE TITLE
Thanks for this.

### ISSUE THREAD

**Issue by clort81** [bbbbbr/gimp-plugin-pixel-art-scalers#13]
Thank you very much for doing this, bbbbbr.  It should have been in main GIMP for decades.

On my devuan ceres linux, building with  libgtk2.0-dev Version: 2.24.33-2 fails with:
```
gcc -c src/filter_dialog.c -o obj/filter_dialog.o -pthread -I/usr/local/include/libpng17 -I/usr/include/gtk-2.0 -I/usr/lib/aarch64-linux-gnu/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/aarch64-linux-gnu -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/uuid -I/usr/include/freetype2 -pthread -I/usr/local/include/libpng17 -I/usr/include/gimp-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/aarch64-linux-gnu -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/gegl-0.4 -I/usr/include/gio-unix-2.0 -I/usr/include/json-glib-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/babl-0.1
In file included from /usr/include/gtk-2.0/gdk/gdkevents.h:34,
                 from /usr/include/gtk-2.0/gdk/gdkdisplay.h:32,
                 from /usr/include/gtk-2.0/gdk/gdkscreen.h:33,
                 from /usr/include/gtk-2.0/gdk/gdkapplaunchcontext.h:31,
                 from /usr/include/gtk-2.0/gdk/gdk.h:32,
                 from /usr/include/gtk-2.0/gtk/gtk.h:32,
                 from /usr/include/gimp-2.0/libgimp/gimpui.h:22,
                 from src/filter_dialog.c:19:
/usr/include/gtk-2.0/gdk/gdkcolor.h:74:3: warning: parameter names (without types) in function declaration
   74 |   gint      GSEAL (size);
      |   ^~~~
/usr/include/gtk-2.0/gdk/gdkcolor.h:74:13: error: field ‘GSEAL’ declared as a function
   74 |   gint      GSEAL (size);
```
The only possibly relevant discussion to GSEAL which I have found (with the now almost completely broken-for-FOSS web search engines)  is here.
https://stackoverflow.com/questions/15569756/how-do-i-get-access-to-gsealed-values-from-gtk-widget-modify-gtkwidgets.
[Not able to insert a link because the new github owners have broken the comment editor for my browser.]

**Comment by bbbbbr** [comment]
Maybe an include path issue? Or the GSEAL macro isn't getting defined?

https://github.com/cryham/ccc/issues/2
http://forum.tinycorelinux.net/index.php?topic=3303.0

It's in gtk-2 on my system but not gtk-3.  Looks like your includes paths all point to gtk-2 though.
$ locate gdkconfig.h
```
/opt/gtkwin/include/gtk-3.0/gdk/gdkconfig.h
/usr/lib/x86_64-linux-gnu/gtk-2.0/include/gdkconfig.h
```

**Comment by clort81** [comment]
I'll try on a virgin install then get back to our package managers; this is a system problem not a bbbbbr problem.  Thanks though.

I use external xbrzscale, but it's great you did this and I hope every gimp user gets to use these by default someday

**Comment by zvezdochiot** [comment]
Hi @clort81 .

See also:
* https://github.com/ImageProcessing-ElectronicPublications/photoquick-examples/tree/main/plugins/transform/upscale
* https://github.com/ImageProcessing-ElectronicPublications/photoquick-plugins/tree/master/src/transform/pixart-scaler
* https://github.com/ImageProcessing-ElectronicPublications/photoquick/releases/tag/4.5.0
