### ISSUE TITLE
Unwanted contour line

### ISSUE THREAD

**Issue by nightmaredream** [bbbbbr/gimp-plugin-pixel-art-scalers#2]
Hi, when i upscale any image, any mode, that has an alpha channel and transparency in it, it makes a contour line of glitched colors from pink to white and so on. I really need a solid line, and i'm batch doing files so i can't just go around and remove these contour lines one by one, it's a skull-scratching issue. Pixel art should Never have glitched contour lines, ever. I can't understand why this plugins isn't pre-fixed about that. IT'S obvious that upscaled sprites needs solid edges. 

Batch-jobbing with Gimp is already a hassle (Using tinytask, doing eveything manually, automated, it's time-expensive)... Adding supplementary tasks such as "create layer mask, posterize mask, go filter, generic, erode, then saving, for every files with an alpha channel, consumes a lot of time... hence, your plugin should do solid edges.

**Comment by bbbbbr** [comment]
Hello,

I am not able to reproduce the issue so far.

Can you provide a couple details to help investigate this?

* An example image for which the problem occurs
* An example image (screenshot is fine) showing the undesired output
* The version of GIMP and operating system you are using
* Does this problem also occur for you in both batch and non-batch mode?

Thanks

**Comment by nightmaredream** [comment]
http:/www.nightmaredream.com/up/upscale%20example.zip

Thought i found a fix. When i say "batch" i mean, i used Tinytask to repeat actions. Because Gimp's batch is totally outdated and has almost no features at all in it. Or it's just overcomplicated and there's no simple way to build a task list i couldn't tell but it'S nothing user-friendly to say the least.

So the fix is that i go Layer > Transparency > threashold alpha.... That fixes the images, but only After they're created thought, which is a problem.

So... Soft edges aren't the biggest issues, but the fact pixel color of soft edges isn't the same color as the object is a problem... If anti aliasing was bleeding the same paint color as the rest of its surroundings, it would be much lesser a problem, thought, hard edges with same bleeding color as surroundings would be much better. I assume both options should be available. hard edges, colored soft edges

So yeah.... I had TinyTask to fix images one by one in gimp... saving as each files, confirming every png export prompts and so on... lmao...

Also suggestion: Do you think you could add a noise module that adds noise between rescaling stages? Say, if it was done in multiple stages. XNview's "pointillize" and "median box" are examples that might give some nice noise/denoise`

Oh, another tip for perfect upscaling: Try adding an imaginary margin all around image so border pixels doesn'T bleed strangely. 

Even thought, if you make a "seamless" mode, it would be amazing, so that upscale becomes border-safe.

**Comment by bbbbbr** [comment]
Maybe there is some difference between how my version of GIMP and yours is rendering the border alpha pixels? 

In all of the images you sent, and after I upscaled the original version, the partially transparent border pixels look correct (in both GIMP and Photoshop) and don't exhibit unwanted aliasing or glitching.

![pixel_scalers_plugin_alpha_issue_001](https://user-images.githubusercontent.com/8322401/69891677-1e98d580-12b3-11ea-9532-251bd7fc0b99.png)
![pixel_scalers_plugin_alpha_issue_002](https://user-images.githubusercontent.com/8322401/69891678-1f316c00-12b3-11ea-91c4-01a143fa6df6.png)

**Comment by nightmaredream** [comment]
I'm usng HQ4x XBR and i still get bleeding edges.. I'll try pasting clipboard image : 
![image](https://user-images.githubusercontent.com/33467930/69891738-cbcc1780-12cc-11ea-9175-14c038499ca7.png)
![algae](https://user-images.githubusercontent.com/33467930/69891742-d38bbc00-12cc-11ea-8715-e0f7be159bf0.png)

**Comment by bbbbbr** [comment]
Strange- should there be red aliasing in the image you posted? I don't see any.

![pixel_scalers_plugin_alpha_issue_003](https://user-images.githubusercontent.com/8322401/69891822-36bd2480-12b4-11ea-9794-c3c0f75622b6.png)

**Comment by nightmaredream** [comment]
Oh... "Red" "bleedding"... Got it. By "bleeding" i mean, it's moist, it spreads around.

**Comment by nightmaredream** [comment]
I'll try updating Gimp to latest

Nope... Already using latest version. 2.10.14

**Comment by bbbbbr** [comment]
To check if I understand - you do not want partial transparency on the edge pixels, just solid colors?  (if source pixels had no transparency)

I think an option to suppress transparency could be added. I will look into it.

(There also appears to be behavior in GIMP where pressing delete on a selection will clear the alpha channel for that area but will not also clear the color for those pixels. This could lead to unwanted and unexpected edge anti-alias fringe colors, when one might expect to mix with just white or black. 

Note to myself- to fix those colors without discarding the alpha channel requires converting the channel to a mask, editing the image, then reconverting the mask to an alpha channel.)

**Comment by nightmaredream** [comment]
I need a solid edge, but i need choice too... But if i would chose aliassed edge, i would like it to be not of the color behind the transparent pixel because these are junk pixels, but of the color of the closest fully opaque pixel.

But yeah, for my cause, i need solid edges, and it has to reject colors coming from alpha 0<>250

**Comment by bbbbbr** [comment]
Here is a build to test which has two options:
 * Allow/Disallow semi-transparent pixels (edge aliasing, alpha < 255)
 * Suppress colors from alpha-hidden pixels (currently alpha <= 32)

The alpha thresholds are not yet configurable. They seem to work in many cases. Ability to change them may be done later.

[plugin_pixel_art_scalers.zip](https://github.com/bbbbbr/gimp-plugin-pixel-art-scalers/files/3907738/plugin_pixel_art_scalers.zip)

**Comment by nightmaredream** [comment]
Hi, i have made tests, it's nearly perfect! It's much better. All it would need is a tolerance slider, then to disallow semi-transparent pixels and make tolerred pixels fully opaque. 
I am testing with this file and it happens to have a few 99.7% opaque pixels. The images are from somebody else, my task is to upscale them for a skin pack and it's either fully opaque or fully transparent, semi transparent pixels causes the game to do visual glitches. It's for a game server with friends, tho when i'll make a final pack, it,ll only contain my files or no-pack-at-all. These as uploaded are for test purpose.

Sooo... Yeah, here's the actual file. 
![bromeliad](https://user-images.githubusercontent.com/33467930/69909031-5cd0ea80-13c2-11ea-8b53-6cb94716d8ad.png)

And the result file. 
![result](https://user-images.githubusercontent.com/33467930/69909095-70308580-13c3-11ea-94df-b65719eb3f1d.png)


You'll notice that some parts of the green stomp are gone, linking the flowers to the grass.

You're almost at it! 

--snip--

But yeah, for the moment, a tolerance slider... Then making every tolerated pixels fully opaque!

**Comment by nightmaredream** [comment]
Seamlessness examples

![coarse_dirt_silty](https://user-images.githubusercontent.com/33467930/69909138-6ce9c980-13c4-11ea-88e3-db63def71b78.png)

![image](https://user-images.githubusercontent.com/33467930/69909149-b1756500-13c4-11ea-8cfd-bca3b70b0dc4.png)


![seamlessresult](https://user-images.githubusercontent.com/33467930/69909161-cfdb6080-13c4-11ea-9148-6b4cdc702190.png)

While it's still a very nice result, seamlessness is broken. 

Another example: (Very good, but broken seamlessness)
![image](https://user-images.githubusercontent.com/33467930/69909180-234dae80-13c5-11ea-801b-7636fb95900a.png)

**Comment by bbbbbr** [comment]
I've opened a separate feature request ticket for your ideas about Seamless Tiling and Image Boundary handling since they are different topics. You can find them here:
https://github.com/bbbbbr/gimp-plugin-pixel-art-scalers/issues/3

**Comment by bbbbbr** [comment]
Here is a build to try. There are now controls for adjusting the threshold of each alpha/opacity handling option.

Correct defaults values (254, 32) in the plug-in dialog may require a one-time restart of GIMP.

[plugin_pixel_art_scalers.dec.01.001.zip](https://github.com/bbbbbr/gimp-plugin-pixel-art-scalers/files/3908749/plugin_pixel_art_scalers.dec.01.001.zip)

**Comment by bbbbbr** [comment]
Commits to implement feature + new binaries:
d397d75d5c19f1b4fd0db69f74e804549a56b902
82ff12ecea2810937e643c80da40d06d916488a0
1dbab1ff11a71fddfe09f9854b8502110f8bde22
b96891def46dfe47503d9527f722a3152e4eab77
