### ISSUE TITLE
dialog?

### ISSUE THREAD

**Issue by zvezdochiot** [bbbbbr/gimp-plugin-pixel-art-scalers#4]
https://github.com/bbbbbr/gimp-plugin-pixel-art-scalers/blob/b96891def46dfe47503d9527f722a3152e4eab77/src/filter_dialog.c#L197-L206
![You dialog](https://i111.fastpic.ru/big/2019/1203/79/292d259852fe2161b45aacfe3abf6c79.png)

Maybe?:
```c
    // Attach the label and combo to the table and show them all
    gtk_table_attach_defaults (GTK_TABLE (settings_table), settings_scaler_label, 0, 1, 0, 1); // Left side of table
    gtk_table_attach_defaults (GTK_TABLE (settings_table), settings_scaler_combo, 1, 2, 0, 1); // Left side of table

    gtk_table_attach_defaults (GTK_TABLE (settings_table), settings_semi_transparency_checkbutton, 0, 1, 1, 2); // Left side of table
    gtk_table_attach_defaults (GTK_TABLE (settings_table), settings_semi_transparency_spinbutton, 1, 2, 1, 2); // Left side of table

    gtk_table_attach_defaults (GTK_TABLE (settings_table), settings_hidden_colors_checkbutton, 0, 1, 2, 3);     // Left side of table
    gtk_table_attach_defaults (GTK_TABLE (settings_table), settings_hidden_colors_spinbutton, 1, 2, 2, 3);     // Left side of table

```
![Fixed dialog](https://i111.fastpic.ru/big/2019/1203/06/216e712a9885b2e379cacd8103070c06.png)

**Comment by bbbbbr** [comment]
Thanks for the suggestion. I gave it a try in a modified form (had to add a gtk_alignment to left align the checkbuttons on the table.)

With the addition of the Border Options dropdown, I ended up still liking a horizontal layout better. With an added space and some padding options adjusted, there is now a gap between the controls that improves the appearance.

![pixel_scaler_screenshot_vert_layout](https://user-images.githubusercontent.com/8322401/70379946-ce3ffa00-18e8-11ea-9384-effbdcabc8c9.png)
![pixel_scaler_screenshot_horiz_layout](https://user-images.githubusercontent.com/8322401/70379947-ce3ffa00-18e8-11ea-981b-98c351ec6137.png)
