### ISSUE TITLE
Final scaled image size is incorrect (cropped)

### ISSUE THREAD

**Issue by zvezdochiot** [bbbbbr/gimp-plugin-pixel-art-scalers#5]
Lena.png: 512x512

![GIMP, lena.png](https://i111.fastpic.ru/big/2019/1213/12/e37afe11db586d2c47f2065a50c6f112.jpg)

Filter -> Render -> Pixel Art Scalers

![GIMP Image Editor using Pixel Art Scalers Plugin](https://i111.fastpic.ru/big/2019/1213/9c/e7d1852ef3246c64072b7af1b88d669c.jpg)

-> GIMP

![GIMP, result](https://i111.fastpic.ru/big/2019/1213/4f/6f45207552af7439175383a99bfb284f.jpg)

Result: 400x400

**Comment by bbbbbr** [comment]
When the source image navigator had scrollbars and was set to the upper-left most, then final output would fail to re-size and apply. My testing must have only been with images smaller than the navigator window.

Fix: b037e51528ceffdd71d410309589dc280b659274

**Comment by zvezdochiot** [comment]
@bbbbbr say:
>Fix: b037e51

And where is the graphic confirmation on the standard test image "Lena"?

**Comment by bbbbbr** [comment]
I would hope it doesn't have special Lena detection :)

**Comment by bbbbbr** [comment]
You're welcome to confirm the fix that way if you'd like
