### ISSUE TITLE
Unable to install on Win 64 bit

### ISSUE THREAD

**Issue by RomajiQuadhash** [bbbbbr/gimp-plugin-pixel-art-scalers#6]
First error message is:
![image](https://user-images.githubusercontent.com/15694394/75079973-9bb1a080-54d8-11ea-9dd7-49b60518c837.png)
The second is the same
the third is:
![image](https://user-images.githubusercontent.com/15694394/75080011-ba179c00-54d8-11ea-9faf-4eddf393fd9a.png)
Fourth is:
![image](https://user-images.githubusercontent.com/15694394/75080040-ce5b9900-54d8-11ea-98e7-61c9592138b5.png)

And then it closes. It is not telling me where it is looking, or lets me try somewhere else

**Comment by bbbbbr** [comment]
Are you trying to run the plugin from within GIMP? If not then you will need to install GIMP version 2.10.12 or later, and copy the plugin to the following folder (location may vary somewhat):
C:\Program Files\GIMP 2\lib\gimp\2.0\plug-ins

If you do have GIMP installed and are starting the program from inside it, what version of GIMP do you have?
