### ISSUE TITLE
MacOS + homebrew Build instructions

### ISSUE THREAD

**Issue by forivall** [bbbbbr/gimp-plugin-pixel-art-scalers#7]
Apparently, [macports is also an option](https://github.com/bootchk/resynthesizer/issues/23#issuecomment-497910863), but I use homebrew and i didn't want to mix the two package managers.

Luckily, @ryan-robeson set up a tap which includes libgimp (for https://github.com/bootchk/resynthesizer), and installing it allowed `make` to work. https://gist.github.com/ryan-robeson/5841f712ff23c910bbbfac793c16bfad#3---install-dependencies

And the default directory to install the plugin is `~/Library/Application\ Support/GIMP/2.10/plug-ins`

And it works!

I can submit a simple PR to update the readme.

**Comment by bbbbbr** [comment]
Cool! Please do.

**Comment by ryan-robeson** [comment]
Hey! That's awesome!

I just pushed an update for libgimp to 2.10.18. Happy to help if that causes any issues.

Also, @bbbbbr, mind if I add a formula for your plugin to my tap?

**Comment by bbbbbr** [comment]
@ryan-robeson : Sounds great. Reference to that could be included in the proposed Readme changes.
You may want to use a release tag to help ensure it's buildable, such as: https://github.com/bbbbbr/gimp-plugin-pixel-art-scalers/releases/tag/v1.1

**Comment by bbbbbr** [comment]
@forivall Would you be interested in testing the plugin build against the libgimp 2.10.18 updates?

**Comment by ryan-robeson** [comment]
@bbbbbr thanks!

You can see the release here: https://github.com/ryan-robeson/homebrew-gimp/releases/tag/v1.3

Installing with homebrew should only require running `brew install ryan-robeson/gimp/pixel-art-scalers`. Then adding the new plugin folder to GIMP's settings.

Everything should be precompiled via bottles. If you or @forivall are able to test this, and run into anything trying to compile from source, please let me know.

**Comment by bbbbbr** [comment]
Added to Readme in 21ec310873e8a5954ff07127143c5ce24ff0fcc5

Thanks again, both of you! @forivall @ryan-robeson
